
-- institucion

insert into institucion (id_institucion, nombre, fecha, direccion, telefono) values (1, 'Vandervort-Dach', '9/10/2023', 'Đà Bắc', '+84-401-137-7229');
insert into institucion (id_institucion, nombre, fecha, direccion, telefono) values (2, 'Schimmel-Legros', '4/26/2022', 'Hongyansi', '+86-419-667-1586');
insert into institucion (id_institucion, nombre, fecha, direccion, telefono) values (3, 'Kohler-Kuhn', '6/6/2023', 'Lima', '+51-156-305-5276');
insert into institucion (id_institucion, nombre, fecha, direccion, telefono) values (4, 'Bogan LLC', '12/16/2020', 'Shancheng', '+86-273-799-7859');
insert into institucion (id_institucion, nombre, fecha, direccion, telefono) values (5, 'Wuckert, Schoen and Jacobs', '12/20/2021', 'Tessaoua', '+227-389-985-0436');
insert into institucion (id_institucion, nombre, fecha, direccion, telefono) values (6, 'Hartmann, Hermann and Lynch', '6/5/2022', 'Chư Prông', '+84-126-261-0308');
insert into institucion (id_institucion, nombre, fecha, direccion, telefono) values (7, 'Ortiz-Beer', '5/4/2020', 'Solsona', '+63-161-526-0721');
insert into institucion (id_institucion, nombre, fecha, direccion, telefono) values (8, 'Dibbert and Sons', '8/3/2022', 'Wiślica', '+48-604-405-5601');
insert into institucion (id_institucion, nombre, fecha, direccion, telefono) values (9, 'Klein LLC', '2/5/2020', 'Monte Novo', '+351-607-943-5053');
insert into institucion (id_institucion, nombre, fecha, direccion, telefono) values (10, 'Kuhic-Kling', '3/27/2022', 'Rzozów', '+48-346-926-4313');
insert into institucion (id_institucion, nombre, fecha, direccion, telefono) values (11, 'Donnelly Inc', '6/17/2022', 'Krajan', '+62-625-819-2052');
insert into institucion (id_institucion, nombre, fecha, direccion, telefono) values (12, 'Bosco, Thompson and Maggio', '12/6/2019', 'Jiulong', '+86-647-544-1395');
insert into institucion (id_institucion, nombre, fecha, direccion, telefono) values (13, 'Sauer, Cummings and Mante', '2/15/2022', 'Palaífyto', '+30-681-175-2472');
insert into institucion (id_institucion, nombre, fecha, direccion, telefono) values (14, 'Rosenbaum, Wunsch and Satterfield', '4/16/2022', 'Yarīm', '+967-689-503-6665');
insert into institucion (id_institucion, nombre, fecha, direccion, telefono) values (15, 'Hilpert LLC', '10/5/2020', 'Lampihung', '+62-867-894-2476');
insert into institucion (id_institucion, nombre, fecha, direccion, telefono) values (16, 'Stroman, Mitchell and Hyatt', '6/4/2020', 'Az Zāhir', '+967-940-727-0440');
insert into institucion (id_institucion, nombre, fecha, direccion, telefono) values (17, 'Friesen, Tillman and Quitzon', '4/4/2021', 'Lhuentse', '+975-982-717-9503');
insert into institucion (id_institucion, nombre, fecha, direccion, telefono) values (18, 'Lakin-Moore', '8/25/2022', 'Nagano-shi', '+81-530-902-8623');
insert into institucion (id_institucion, nombre, fecha, direccion, telefono) values (19, 'Sawayn, O''Hara and Sporer', '3/29/2021', 'Falun', '+46-539-900-9186');
insert into institucion (id_institucion, nombre, fecha, direccion, telefono) values (20, 'Monahan Group', '12/14/2020', 'Xinwu', '+86-712-325-1609');

select * from institucion;

--usuario
insert into usuario (id, email, password, rol, id_institucion) values (1, 'agitsham0@google.pl', 'hG8''', 'VOLUNTARIO', '11');
insert into usuario (id, email, password, rol, id_institucion) values (2, 'hsnookes1@earthlink.net', 'bV3$fh', 'VOLUNTARIO', '15');
insert into usuario (id, email, password, rol, id_institucion) values (3, 'mmaccrosson2@printfriendly.com', 'wH6_aw', 'INSTITUCION', '12');
insert into usuario (id, email, password, rol, id_institucion) values (4, 'ociccetti3@issuu.com', 'bS0#W', 'VOLUNTARIO', '19');
insert into usuario (id, email, password, rol, id_institucion) values (5, 'dschapero4@desdev.cn', 'gA8\6_+Q', 'VOLUNTARIO', '6');
insert into usuario (id, email, password, rol, id_institucion) values (6, 'ecranch5@fotki.com', 'xO7~#', 'VOLUNTARIO', '5');
insert into usuario (id, email, password, rol, id_institucion) values (7, 'gbayliss6@google.com', 'jY3*M', 'INSTITUCION', '9');
insert into usuario (id, email, password, rol, id_institucion) values (8, 'rethridge7@cisco.com', 'kD7.O9YU', 'VOLUNTARIO', '8');
insert into usuario (id, email, password, rol, id_institucion) values (9, 'kluquet8@unesco.org', 'qY8}', 'VOLUNTARIO', '10');
insert into usuario (id, email, password, rol, id_institucion) values (10, 'jstenson9@wikipedia.org', 'bU9)2N+r', 'INSTITUCION', '17');
insert into usuario (id, email, password, rol, id_institucion) values (11, 'acrinagea@ask.com', 'rD3}85', 'INSTITUCION', '13');
insert into usuario (id, email, password, rol, id_institucion) values (12, 'wwoodingtonb@columbia.edu', 'uB6}Df2Q', 'INSTITUCION', '1');
insert into usuario (id, email, password, rol, id_institucion) values (13, 'besslementc@hubpages.com', 'bW0''\~', 'VOLUNTARIO', '7');
insert into usuario (id, email, password, rol, id_institucion) values (14, 'fchalonerd@squarespace.com', 'nK8''#%Qd', 'INSTITUCION', '20');
insert into usuario (id, email, password, rol, id_institucion) values (15, 'wastine@nba.com', 'iL2#<_d=', 'VOLUNTARIO', '14');
insert into usuario (id, email, password, rol, id_institucion) values (16, 'ncluesf@privacy.gov.au', 'dS9#J|', 'INSTITUCION', '2');
insert into usuario (id, email, password, rol, id_institucion) values (17, 'bsandisong@cisco.com', 'hE6(', 'INSTITUCION', '3');
insert into usuario (id, email, password, rol, id_institucion) values (18, 'hfennh@army.mil', 'mB5@9vm|', 'VOLUNTARIO', '18');
insert into usuario (id, email, password, rol, id_institucion) values (19, 'chritzkoi@elpais.com', 'cN0(O', 'VOLUNTARIO', '4');
insert into usuario (id, email, password, rol, id_institucion) values (20, 'rtorrentj@google.pl', 'gD0\RDbc', 'INSTITUCION', '16');
insert into usuario (id, email, password, rol, id_institucion) values (21, 'kslyk@trellian.com', 'lT0~J', 'INSTITUCION', '1');
insert into usuario (id, email, password, rol, id_institucion) values (22, 'kwoodingtonl@histats.com', 'iP5+W', 'INSTITUCION', '3');
insert into usuario (id, email, password, rol, id_institucion) values (23, 'jwoodthorpem@123-reg.co.uk', 'eI0<bvz5', 'VOLUNTARIO', '6');
insert into usuario (id, email, password, rol, id_institucion) values (24, 'owigleyn@dyndns.org', 'rB4|UZ', 'VOLUNTARIO', '11');
insert into usuario (id, email, password, rol, id_institucion) values (25, 'mtiverso@dyndns.org', 'lJ0|a', 'VOLUNTARIO', '19');
insert into usuario (id, email, password, rol, id_institucion) values (26, 'ccattrellp@timesonline.co.uk', 'jR8''VI@{', 'INSTITUCION', '13');
insert into usuario (id, email, password, rol, id_institucion) values (27, 'ncliffq@theguardian.com', 'mT0#Y66%', 'INSTITUCION', '18');
insert into usuario (id, email, password, rol, id_institucion) values (28, 'rkelmerer@theatlantic.com', 'hG7@0J1', 'VOLUNTARIO', '14');
insert into usuario (id, email, password, rol, id_institucion) values (29, 'nsikoras@phpbb.com', 'cM2#v', 'INSTITUCION', '8');
insert into usuario (id, email, password, rol, id_institucion) values (30, 'cmiddlemisst@fema.gov', 'qZ8$sw', 'VOLUNTARIO', '15');
insert into usuario (id, email, password, rol, id_institucion) values (31, 'tcostiganu@google.com.br', 'qG4~JgdZ', 'VOLUNTARIO', '20');
insert into usuario (id, email, password, rol, id_institucion) values (32, 'bvillav@tinypic.com', 'eR2.T(nO', 'VOLUNTARIO', '12');
insert into usuario (id, email, password, rol, id_institucion) values (33, 'nkrusew@simplemachines.org', 'mJ2#qJv', 'VOLUNTARIO', '5');
insert into usuario (id, email, password, rol, id_institucion) values (34, 'kgajewskix@php.net', 'tW8>AD', 'INSTITUCION', '7');
insert into usuario (id, email, password, rol, id_institucion) values (35, 'gkaspary@bbc.co.uk', 'pD2%9(', 'VOLUNTARIO', '4');
insert into usuario (id, email, password, rol, id_institucion) values (36, 'kpragnallz@dion.ne.jp', 'wQ1?bdd', 'VOLUNTARIO', '17');
insert into usuario (id, email, password, rol, id_institucion) values (37, 'nklimov10@boston.com', 'zI0\e', 'INSTITUCION', '16');
insert into usuario (id, email, password, rol, id_institucion) values (38, 'fmerchant11@archive.org', 'lT8*\q', 'INSTITUCION', '2');
insert into usuario (id, email, password, rol, id_institucion) values (39, 'rvasilchenko12@mit.edu', 'nN0.p', 'INSTITUCION', '10');
insert into usuario (id, email, password, rol, id_institucion) values (40, 'dneubigin13@sbwire.com', 'xR7"7w', 'INSTITUCION', '9');
insert into usuario (id, email, password, rol, id_institucion) values (41, 'nmoss14@chron.com', 'qL4~G', 'VOLUNTARIO', '17');
insert into usuario (id, email, password, rol, id_institucion) values (42, 'cpurviss15@whitehouse.gov', 'yT4{Du/', 'INSTITUCION', '18');
insert into usuario (id, email, password, rol, id_institucion) values (43, 'kmcclifferty16@oracle.com', 'tQ6.59L', 'INSTITUCION', '12');
insert into usuario (id, email, password, rol, id_institucion) values (44, 'cwalkowski17@usatoday.com', 'sX0*', 'VOLUNTARIO', '10');
insert into usuario (id, email, password, rol, id_institucion) values (45, 'eclunan18@purevolume.com', 'dW2#(<', 'INSTITUCION', '2');
insert into usuario (id, email, password, rol, id_institucion) values (46, 'gclayfield19@merriam-webster.com', 'lD9"tWg`', 'VOLUNTARIO', '1');
insert into usuario (id, email, password, rol, id_institucion) values (47, 'rsacase1a@friendfeed.com', 'kQ2\', 'VOLUNTARIO', '11');
insert into usuario (id, email, password, rol, id_institucion) values (48, 'mkybird1b@alibaba.com', 'wT7=|', 'INSTITUCION', '19');
insert into usuario (id, email, password, rol, id_institucion) values (49, 'mhacard1c@rakuten.co.jp', 'oM2>Gc', 'VOLUNTARIO', '6');
insert into usuario (id, email, password, rol, id_institucion) values (50, 'dalf1d@nasa.gov', 'kT5|SN@2', 'INSTITUCION', '7');
insert into usuario (id, email, password, rol, id_institucion) values (51, 'vpiatto1e@miibeian.gov.cn', 'mT8~', 'VOLUNTARIO', '3');
insert into usuario (id, email, password, rol, id_institucion) values (52, 'cpietri1f@bloglines.com', 'pJ8(', 'INSTITUCION', '15');
insert into usuario (id, email, password, rol, id_institucion) values (53, 'lhelmke1g@tiny.cc', 'jH1&50r', 'INSTITUCION', '20');
insert into usuario (id, email, password, rol, id_institucion) values (54, 'bcullen1h@istockphoto.com', 'qI5!sNK}', 'VOLUNTARIO', '14');
insert into usuario (id, email, password, rol, id_institucion) values (55, 'tborless1i@ocn.ne.jp', 'wV6>j3oI', 'INSTITUCION', '5');
insert into usuario (id, email, password, rol, id_institucion) values (56, 'obugler1j@seesaa.net', 'kU9+9', 'INSTITUCION', '4');
insert into usuario (id, email, password, rol, id_institucion) values (57, 'aleason1k@google.com.br', 'oE5$', 'VOLUNTARIO', '8');
insert into usuario (id, email, password, rol, id_institucion) values (58, 'ygres1l@squarespace.com', 'kQ1&pp5', 'VOLUNTARIO', '13');
insert into usuario (id, email, password, rol, id_institucion) values (59, 'aalyonov1m@storify.com', 'bE0!7', 'VOLUNTARIO', '9');
insert into usuario (id, email, password, rol, id_institucion) values (60, 'brawlin1n@ocn.ne.jp', 'sY4<w', 'VOLUNTARIO', '16');
insert into usuario (id, email, password, rol, id_institucion) values (61, 'dgamlin1o@discovery.com', 'eQ6\><"', 'INSTITUCION', '9');
insert into usuario (id, email, password, rol, id_institucion) values (62, 'mwannop1p@histats.com', 'iM9(=l', 'INSTITUCION', '10');
insert into usuario (id, email, password, rol, id_institucion) values (63, 'akording1q@gnu.org', 'bP9.9)R', 'VOLUNTARIO', '11');
insert into usuario (id, email, password, rol, id_institucion) values (64, 'jherrieven1r@businessweek.com', 'eF2''', 'VOLUNTARIO', '14');
insert into usuario (id, email, password, rol, id_institucion) values (65, 'bdoogue1s@ucoz.com', 'zB5(rKb', 'INSTITUCION', '6');
insert into usuario (id, email, password, rol, id_institucion) values (66, 'jbagley1t@marriott.com', 'iU0~', 'VOLUNTARIO', '18');
insert into usuario (id, email, password, rol, id_institucion) values (67, 'igalego1u@blogs.com', 'nU0''J', 'INSTITUCION', '3');
insert into usuario (id, email, password, rol, id_institucion) values (68, 'gekins1v@wikimedia.org', 'oS5+', 'VOLUNTARIO', '1');
insert into usuario (id, email, password, rol, id_institucion) values (69, 'zschechter1w@cornell.edu', 'gZ7)SKX', 'VOLUNTARIO', '16');
insert into usuario (id, email, password, rol, id_institucion) values (70, 'eteers1x@go.com', 'dK5#}z', 'INSTITUCION', '4');
insert into usuario (id, email, password, rol, id_institucion) values (71, 'alinde1y@cpanel.net', 'bO4_', 'INSTITUCION', '12');
insert into usuario (id, email, password, rol, id_institucion) values (72, 'sscowcraft1z@economist.com', 'hJ0|\''rl', 'INSTITUCION', '2');
insert into usuario (id, email, password, rol, id_institucion) values (73, 'nhinners20@csmonitor.com', 'rT4~Y', 'INSTITUCION', '13');
insert into usuario (id, email, password, rol, id_institucion) values (74, 'rainsley21@unicef.org', 'gP8<G=', 'INSTITUCION', '7');
insert into usuario (id, email, password, rol, id_institucion) values (75, 'mclemenceau22@list-manage.com', 'tK1!', 'INSTITUCION', '17');
insert into usuario (id, email, password, rol, id_institucion) values (76, 'thaugen23@51.la', 'gD9?SB', 'INSTITUCION', '19');
insert into usuario (id, email, password, rol, id_institucion) values (77, 'kfreeburn24@slate.com', 'zA8!wP', 'VOLUNTARIO', '20');
insert into usuario (id, email, password, rol, id_institucion) values (78, 'jrottery25@vistaprint.com', 'xB8$CD', 'INSTITUCION', '8');
insert into usuario (id, email, password, rol, id_institucion) values (79, 'ohinckes26@shop-pro.jp', 'kP6{x<', 'VOLUNTARIO', '5');
insert into usuario (id, email, password, rol, id_institucion) values (80, 'nhaddacks27@1688.com', 'tA1.Wv', 'INSTITUCION', '15');
insert into usuario (id, email, password, rol, id_institucion) values (81, 'tchippin28@tuttocitta.it', 'sG4#I', 'INSTITUCION', '16');
insert into usuario (id, email, password, rol, id_institucion) values (82, 'trottgers29@uiuc.edu', 'iY3"R&sy', 'VOLUNTARIO', '11');
insert into usuario (id, email, password, rol, id_institucion) values (83, 'kciccotto2a@phpbb.com', 'xW1''', 'INSTITUCION', '5');
insert into usuario (id, email, password, rol, id_institucion) values (84, 'rbagenal2b@soundcloud.com', 'oT1!Zc.''', 'VOLUNTARIO', '8');
insert into usuario (id, email, password, rol, id_institucion) values (85, 'nchatenier2c@csmonitor.com', 'gB2~6,m9', 'INSTITUCION', '14');
insert into usuario (id, email, password, rol, id_institucion) values (86, 'emcclarence2d@bluehost.com', 'jY5}AdZ', 'VOLUNTARIO', '3');
insert into usuario (id, email, password, rol, id_institucion) values (87, 'kzanetti2e@buzzfeed.com', 'jF8@c', 'INSTITUCION', '6');
insert into usuario (id, email, password, rol, id_institucion) values (88, 'gmountford2f@unesco.org', 'cC7&', 'INSTITUCION', '19');
insert into usuario (id, email, password, rol, id_institucion) values (89, 'bbartkiewicz2g@gmpg.org', 'wX7{c!b', 'INSTITUCION', '10');
insert into usuario (id, email, password, rol, id_institucion) values (90, 'edaal2h@cloudflare.com', 'gH5`F!Z', 'VOLUNTARIO', '9');
insert into usuario (id, email, password, rol, id_institucion) values (91, 'lpatroni2i@fastcompany.com', 'mN5\', 'INSTITUCION', '1');
insert into usuario (id, email, password, rol, id_institucion) values (92, 'gbouts2j@scientificamerican.com', 'cC0%ji', 'VOLUNTARIO', '12');
insert into usuario (id, email, password, rol, id_institucion) values (93, 'mdanihelka2k@vistaprint.com', 'aA7?$my4', 'INSTITUCION', '15');
insert into usuario (id, email, password, rol, id_institucion) values (94, 'ukenner2l@behance.net', 'xB7''x$Bz', 'VOLUNTARIO', '4');
insert into usuario (id, email, password, rol, id_institucion) values (95, 'fporcher2m@telegraph.co.uk', 'pN5?n', 'VOLUNTARIO', '2');
insert into usuario (id, email, password, rol, id_institucion) values (96, 'ccastane2n@unc.edu', 'nS8.JHp', 'VOLUNTARIO', '20');
insert into usuario (id, email, password, rol, id_institucion) values (97, 'sastbury2o@arizona.edu', 'iI9,', 'VOLUNTARIO', '18');
insert into usuario (id, email, password, rol, id_institucion) values (98, 'blongshaw2p@google.it', 'xP1%$', 'INSTITUCION', '13');
insert into usuario (id, email, password, rol, id_institucion) values (99, 'tohenecan2q@businessinsider.com', 'sC9_O#ru', 'INSTITUCION', '17');
insert into usuario (id, email, password, rol, id_institucion) values (100, 'kridd2r@nps.gov', 'vE1|\?I9', 'VOLUNTARIO', '7');

-- voluntario

insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (1, 'Bili', 'Wyrall', '143-150-2820', 'Bočar', '8');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (2, 'Conni', 'Elger', '884-584-7643', 'Jianping', '47');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (3, 'Kliment', 'Schrieves', '478-801-0417', 'Huanglong', '60');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (4, 'Quintana', 'Reen', '208-238-3228', 'Bantian', '15');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (5, 'Isabelle', 'Dyson', '881-820-5231', 'Auriflama', '86');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (6, 'Even', 'Brainsby', '753-601-6117', 'Parintins', '88');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (7, 'Stace', 'Guidotti', '277-494-4141', 'Bolkhov', '32');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (8, 'Nevsa', 'Kingett', '705-170-3152', 'Pingdong', '62');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (9, 'Kali', 'Tunnah', '490-703-3537', 'Jasienica Rosielna', '74');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (10, 'Penny', 'Coulthurst', '663-273-7531', 'Longtang', '48');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (11, 'Alison', 'Cordelle', '930-496-7759', 'Suka Makmue', '30');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (12, 'Kev', 'Orchart', '389-970-9261', 'Pamplona', '16');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (13, 'Kennedy', 'Bunt', '606-606-7970', 'Puricay', '87');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (14, 'Travis', 'Bredgeland', '254-849-1445', 'Cartagena', '67');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (15, 'Marysa', 'Damsell', '596-431-5289', 'Yangxipu', '23');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (16, 'Blythe', 'Fysh', '964-786-0529', 'Thị Trấn Ngan Dừa', '82');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (17, 'Sherill', 'Beernt', '841-309-1376', 'Darmasari', '43');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (18, 'Hermione', 'Keuneke', '717-407-1883', 'Verkhnyaya Toyma', '45');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (19, 'Terri-jo', 'Totman', '709-858-1895', 'Sabadell', '73');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (20, 'Jackson', 'Sherer', '210-365-1603', 'Sakai', '24');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (21, 'Flossy', 'Huggett', '331-564-8052', 'Iniö', '64');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (22, 'Sharla', 'Turfitt', '209-918-7767', 'Kinnegad', '46');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (23, 'Kurt', 'Neggrini', '548-676-2703', 'Longcheng', '31');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (24, 'Adriena', 'Parrington', '400-432-3573', 'Selorejo', '38');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (25, 'Amalie', 'Swaite', '835-221-6972', 'Daqingshan', '28');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (26, 'Marlow', 'Oxberry', '574-310-0507', 'Madagali', '100');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (27, 'Kimberli', 'Belitz', '662-576-2301', 'Gorbunki', '34');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (28, 'Madelene', 'Keepin', '504-263-2857', 'Lunéville', '59');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (29, 'Hieronymus', 'Skoate', '889-274-3959', 'Sakhnīn', '68');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (30, 'Teddi', 'Trethowan', '611-918-5177', 'Wangfu', '42');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (31, 'Horton', 'Izon', '225-946-5311', 'Baton Rouge', '49');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (32, 'Lancelot', 'Pontefract', '214-140-5694', 'Dallas', '4');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (33, 'Reiko', 'Gildersleeve', '654-168-8635', 'Acacías', '92');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (34, 'Beatrice', 'Alloway', '620-928-4987', 'Shah Alam', '36');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (35, 'Robby', 'Spon', '231-117-5752', 'Kashin', '90');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (36, 'Eulalie', 'Minall', '461-380-4866', 'Kovel’', '19');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (37, 'Keriann', 'Whiston', '377-303-2958', 'Douala', '99');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (38, 'Holli', 'Weber', '702-197-4514', 'Carenang Lor', '91');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (39, 'Alwyn', 'Kief', '652-272-1490', 'Kulaman', '78');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (40, 'Catherine', 'Bullus', '170-671-2551', 'San Isidro', '72');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (41, 'Arleen', 'Carpenter', '544-426-3508', 'Vale Covo', '37');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (42, 'Faun', 'MacAndie', '186-129-5139', 'A-da-Gorda', '71');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (43, 'Giorgio', 'Berndtssen', '384-221-6004', 'Fontinha', '25');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (44, 'Mack', 'MacWhirter', '865-289-5859', 'Aygestan', '55');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (45, 'Lea', 'Brasher', '610-363-2298', 'Pidvolochys’k', '51');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (46, 'Ebba', 'Guynemer', '699-498-5736', 'Omboué', '29');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (47, 'Royall', 'Grunwald', '469-576-3040', 'Nanfeng', '50');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (48, 'Pansy', 'Cawkill', '131-569-1129', 'Balqash', '58');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (49, 'Fabiano', 'Rich', '350-896-2263', 'Pantin', '96');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (50, 'Marie', 'Inggall', '399-553-3076', 'Buan', '69');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (51, 'Franciskus', 'Mucklo', '903-394-0403', 'Sailaitang', '22');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (52, 'Rustin', 'Atterbury', '801-673-2050', 'Provo', '85');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (53, 'Thane', 'Jirousek', '101-107-4255', 'Kaingiwa', '10');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (54, 'Peggie', 'Linsley', '860-189-9622', 'Aragarças', '3');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (55, 'Lenore', 'Starkie', '771-833-6694', 'Dongzhang', '13');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (56, 'Clarice', 'Drogan', '531-460-5042', 'Pirogovo', '93');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (57, 'Pail', 'Lancley', '875-131-1334', 'Ängelholm', '9');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (58, 'Ozzy', 'Polleye', '846-981-8875', 'Hanam', '52');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (59, 'Seumas', 'Winscum', '751-703-2701', 'Hengdaohezi', '53');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (60, 'Sherwood', 'Rehor', '876-771-2741', 'Ceranów', '2');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (61, 'Sherlocke', 'De Marchi', '531-832-0558', 'Camilaca', '20');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (62, 'Anet', 'Mougeot', '899-152-7918', 'Melaka', '40');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (63, 'Marta', 'Bahl', '630-541-9040', 'Agassiz', '98');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (64, 'Alia', 'Steart', '194-848-9228', 'Svetogorsk', '61');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (65, 'Winne', 'Herche', '638-567-3086', 'Tlogowetan', '81');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (66, 'Bev', 'Gager', '518-227-5793', 'Vila Chã', '41');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (67, 'Britte', 'Batchley', '933-593-2635', 'Nunguan', '57');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (68, 'Jeanne', 'Chark', '661-886-8963', 'Shanxia', '83');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (69, 'Jacquetta', 'Eyton', '447-753-3200', 'Gowurdak', '79');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (70, 'Haven', 'Kassel', '360-547-0134', 'Zhentian', '26');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (71, 'Washington', 'Gynn', '260-366-3273', 'San Carlos', '94');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (72, 'Gisella', 'Drewett', '769-570-1724', 'Osapsio', '33');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (73, 'Neddie', 'Burtonwood', '525-108-7496', 'Chak Two Hundred Forty-Nine TDA', '17');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (74, 'Ana', 'Whether', '236-837-3448', 'Kaliterus', '76');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (75, 'Burt', 'Mabley', '481-469-7227', 'Loma Bonita', '95');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (76, 'Andras', 'Vergine', '880-190-8041', 'Bitin', '35');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (77, 'Sondra', 'Ussher', '226-628-3177', 'Jonkowo', '63');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (78, 'Loreen', 'Lenahan', '908-982-7789', 'Karangampel', '65');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (79, 'Horatio', 'Lescop', '628-853-5055', 'Malahide', '66');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (80, 'Giffer', 'Hocking', '321-215-4039', 'Bulqizë', '27');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (81, 'Bartolomeo', 'Colpus', '170-735-1482', 'Paola', '44');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (82, 'Marlo', 'Chalfont', '458-503-8773', 'Asahikawa', '1');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (83, 'Raddy', 'Kemer', '534-805-4665', 'Baiyashi', '75');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (84, 'Kylie', 'Premble', '422-822-6125', 'Poitiers', '70');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (85, 'Duky', 'Wilden', '330-492-2520', 'Chikeng', '84');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (86, 'Kincaid', 'Darinton', '906-387-6074', 'Bajiao', '54');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (87, 'Gerik', 'Tiner', '111-562-3735', 'Wuxia', '97');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (88, 'Kirbee', 'Sanday', '768-443-2714', 'Thompson', '14');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (89, 'Ferdinand', 'Barcroft', '268-860-2031', 'Évry', '77');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (90, 'Harbert', 'Birchill', '920-447-8731', 'Qal‘ah-ye Shāhī', '89');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (91, 'Moises', 'Olenchenko', '546-405-0359', 'San José de Feliciano', '21');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (92, 'Saunder', 'McGahy', '585-503-9067', 'Caijiazha', '5');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (93, 'Rickert', 'Saltmarshe', '555-700-6530', 'Moxi', '80');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (94, 'Kristel', 'Luisetti', '827-329-0166', 'Balekersukamaju', '11');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (95, 'Bobbee', 'Lob', '786-698-5026', 'Palhais', '56');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (96, 'Ninon', 'Lawrenceson', '554-405-1969', 'Sanbaishan', '6');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (97, 'Carline', 'MacGowing', '891-989-4766', 'Muara Dua', '12');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (98, 'Eward', 'Kuhwald', '540-479-9108', 'Tanjungbalai', '39');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (99, 'Brynn', 'Dalyell', '361-275-9281', 'Weiyanggong', '7');
insert into voluntario (id_voluntario, nombre, apellido, telefono, direccion, id_usuario) values (100, 'Sal', 'Gorham', '782-748-3951', 'Murree', '80');


select * from voluntario


-- emergencia

    insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (1, 'Indigo', 'Green', 'Esquina', '2/20/2023', true, '20');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (2, 'Teal', 'Maroon', 'Lindavista', '12/2/2022', true, '3');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (3, 'Puce', 'Fuscia', 'Limatambo', '3/23/2023', false, '6');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (4, 'Turquoise', 'Blue', 'Nuits-Saint-Georges', '2/24/2023', false, '9');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (5, 'Yellow', 'Violet', 'Huallanca', '7/15/2023', false, '2');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (6, 'Yellow', 'Green', 'Magang', '5/29/2023', true, '11');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (7, 'Aquamarine', 'Goldenrod', 'Gaoqiao', '4/17/2023', true, '7');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (8, 'Red', 'Mauv', 'Den Haag', '11/10/2022', true, '19');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (9, 'Orange', 'Yellow', 'Nong Yasai', '2/24/2023', false, '10');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (10, 'Blue', 'Fuscia', 'Hexing', '6/8/2023', false, '15');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (11, 'Indigo', 'Aquamarine', 'Rumboci', '6/15/2023', false, '5');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (12, 'Crimson', 'Blue', 'Si Thep', '9/19/2023', false, '13');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (13, 'Fuscia', 'Teal', 'Wates', '5/19/2023', true, '12');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (14, 'Goldenrod', 'Blue', 'Puan', '7/16/2023', false, '4');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (15, 'Turquoise', 'Blue', 'Poigar', '8/10/2023', true, '17');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (16, 'Green', 'Goldenrod', 'Kamensk-Ural’skiy', '1/27/2023', true, '8');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (17, 'Fuscia', 'Maroon', 'Jesenice', '9/27/2023', true, '1');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (18, 'Violet', 'Maroon', 'Tiegai', '3/6/2023', false, '14');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (19, 'Yellow', 'Purple', 'Batukuta', '12/4/2022', false, '16');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (20, 'Turquoise', 'Blue', 'Magisterial', '10/21/2022', false, '18');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (21, 'Indigo', 'Khaki', 'Gävle', '8/13/2023', true, '13');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (22, 'Puce', 'Teal', 'Reims', '6/14/2023', true, '1');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (23, 'Pink', 'Green', 'Huaxijie', '10/24/2022', false, '3');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (24, 'Fuscia', 'Purple', 'Zaoshi', '3/26/2023', false, '8');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (25, 'Indigo', 'Khaki', 'Ban Chang', '6/6/2023', true, '9');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (26, 'Green', 'Teal', 'Armenokhórion', '1/4/2023', false, '5');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (27, 'Crimson', 'Orange', 'Sila', '5/15/2023', false, '19');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (28, 'Green', 'Indigo', 'Skuodas', '10/4/2023', false, '2');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (29, 'Green', 'Red', 'Dushanbe', '6/29/2023', false, '16');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (30, 'Maroon', 'Puce', 'Bilbays', '5/28/2023', false, '6');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (31, 'Khaki', 'Violet', 'Tirmiz', '2/23/2023', false, '4');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (32, 'Khaki', 'Pink', 'Clarin', '5/4/2023', true, '11');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (33, 'Mauv', 'Purple', 'Baracatan', '3/10/2023', true, '20');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (34, 'Violet', 'Blue', 'Sara Kunda', '4/7/2023', false, '12');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (35, 'Turquoise', 'Aquamarine', 'Rio de Moinhos', '2/24/2023', true, '14');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (36, 'Teal', 'Puce', 'Nuevo Chamelecón', '4/8/2023', true, '15');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (37, 'Maroon', 'Fuscia', 'Purral', '6/7/2023', false, '10');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (38, 'Violet', 'Pink', 'Stavanger', '3/2/2023', true, '18');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (39, 'Teal', 'Puce', 'Banocboc', '2/11/2023', false, '7');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (40, 'Khaki', 'Yellow', 'Hudong', '8/3/2023', false, '17');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (41, 'Indigo', 'Puce', 'Donostia-San Sebastian', '1/10/2023', false, '3');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (42, 'Purple', 'Goldenrod', 'Sinisian', '11/16/2022', true, '16');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (43, 'Puce', 'Blue', 'Trajouce', '3/12/2023', true, '14');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (44, 'Maroon', 'Blue', 'Los Angeles', '10/8/2023', true, '6');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (45, 'Maroon', 'Indigo', 'Zarya', '4/8/2023', true, '1');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (46, 'Indigo', 'Green', 'Andaray', '11/28/2022', false, '15');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (47, 'Yellow', 'Pink', 'Quba', '7/7/2023', true, '7');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (48, 'Mauv', 'Goldenrod', 'Galūgāh', '10/19/2023', false, '9');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (49, 'Pink', 'Aquamarine', 'Norak', '12/18/2022', true, '20');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (50, 'Pink', 'Khaki', 'Longfeng', '7/5/2023', true, '4');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (51, 'Turquoise', 'Blue', 'Agat Village', '10/21/2022', false, '17');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (52, 'Yellow', 'Indigo', 'Tayug', '12/31/2022', false, '8');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (53, 'Orange', 'Purple', 'Karagach', '11/8/2022', false, '10');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (54, 'Puce', 'Maroon', 'Manukau City', '8/24/2023', true, '5');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (55, 'Aquamarine', 'Aquamarine', 'Duas Igrejas', '10/21/2022', true, '2');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (56, 'Pink', 'Aquamarine', 'Danao', '12/31/2022', true, '12');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (57, 'Yellow', 'Indigo', 'Lingcheng', '1/26/2023', false, '19');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (58, 'Fuscia', 'Mauv', 'Krajan Kerjo', '4/9/2023', true, '18');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (59, 'Violet', 'Indigo', 'Rifu', '9/23/2023', false, '11');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (60, 'Mauv', 'Teal', 'Tonjongsari', '3/16/2023', true, '13');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (61, 'Teal', 'Purple', 'Kuytun', '2/14/2023', true, '3');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (62, 'Purple', 'Aquamarine', 'Chicago', '9/1/2023', false, '5');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (63, 'Yellow', 'Goldenrod', 'Quintã', '6/17/2023', true, '15');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (64, 'Red', 'Maroon', 'El Rosario', '8/13/2023', true, '17');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (65, 'Green', 'Purple', 'Dingtao', '12/1/2022', false, '9');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (66, 'Red', 'Goldenrod', 'Huddinge', '9/17/2023', true, '12');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (67, 'Khaki', 'Mauv', 'San Antonio', '12/9/2022', true, '19');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (68, 'Mauv', 'Blue', 'Zhuangke', '4/6/2023', false, '11');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (69, 'Mauv', 'Violet', 'Stockton', '7/18/2023', true, '18');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (70, 'Khaki', 'Teal', 'Peremyshl’', '9/10/2023', false, '14');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (71, 'Puce', 'Blue', 'Shadrinsk', '8/31/2023', true, '8');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (72, 'Puce', 'Indigo', 'Longcang', '7/17/2023', false, '7');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (73, 'Blue', 'Puce', 'Beidong', '4/20/2023', false, '1');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (74, 'Yellow', 'Khaki', 'Liuhe', '2/13/2023', false, '16');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (75, 'Aquamarine', 'Puce', 'Kuantan', '9/1/2023', false, '10');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (76, 'Indigo', 'Puce', 'General Luna', '10/25/2022', true, '20');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (77, 'Mauv', 'Yellow', 'Vanves', '10/17/2023', true, '6');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (78, 'Aquamarine', 'Maroon', 'Wangbuzhuang', '2/20/2023', false, '13');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (79, 'Purple', 'Turquoise', 'Shiqiao', '11/5/2022', true, '2');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (80, 'Turquoise', 'Orange', 'Lae', '9/29/2023', true, '4');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (81, 'Fuscia', 'Goldenrod', 'Port-Gentil', '2/15/2023', true, '17');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (82, 'Yellow', 'Khaki', 'Yumbe', '2/3/2023', false, '9');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (83, 'Teal', 'Indigo', 'Hengliang', '8/25/2023', false, '4');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (84, 'Turquoise', 'Blue', 'Naru', '9/25/2023', false, '5');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (85, 'Violet', 'Fuscia', 'An Nāşirah', '7/11/2023', true, '15');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (86, 'Goldenrod', 'Aquamarine', 'Riosucio', '9/2/2023', false, '6');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (87, 'Fuscia', 'Maroon', 'Eystur', '4/27/2023', true, '8');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (88, 'Violet', 'Goldenrod', 'Kotor', '2/28/2023', true, '13');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (89, 'Red', 'Crimson', 'Goim', '5/20/2023', true, '16');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (90, 'Green', 'Pink', 'Quảng Yên', '1/24/2023', true, '7');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (91, 'Blue', 'Blue', 'Eaton', '5/3/2023', true, '20');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (92, 'Aquamarine', 'Mauv', 'Atamyrat', '6/16/2023', true, '14');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (93, 'Teal', 'Blue', 'Yushu', '12/16/2022', true, '11');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (94, 'Orange', 'Aquamarine', 'Lipin Bor', '2/22/2023', true, '18');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (95, 'Turquoise', 'Mauv', 'Tongzha', '6/23/2023', false, '2');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (96, 'Teal', 'Pink', 'Meru', '9/23/2023', true, '19');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (97, 'Teal', 'Purple', 'Xin’andu', '5/31/2023', false, '10');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (98, 'Teal', 'Crimson', 'Luleå', '8/13/2023', false, '3');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (99, 'Teal', 'Purple', 'Bayawan', '4/30/2023', true, '12');
insert into emergencia (id_emergencia, asunto, descripcion, direccion, fecha, activa, id_institucion) values (100, 'Khaki', 'Turquoise', 'Solna', '5/28/2023', false, '1');

-- tarea

insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (1, 'urgente', true, '100');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (2, 'incendio', false, '99');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (3, 'importante', true, '10');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (4, 'urgente', false, '12');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (5, 'incendio', true, '21');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (6, 'importante', false, '49');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (7, 'importante', true, '72');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (8, 'urgente', false, '77');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (9, 'incendio', false, '40');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (10, 'incendio', true, '82');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (11, 'incendio', false, '37');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (12, 'incendio', false, '50');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (13, 'urgente', true, '91');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (14, 'importante', false, '90');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (15, 'incendio', true, '42');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (16, 'urgente', true, '43');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (17, 'urgente', false, '76');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (18, 'urgente', false, '83');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (19, 'importante', true, '54');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (20, 'urgente', true, '87');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (21, 'urgente', true, '39');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (22, 'incendio', true, '69');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (23, 'importante', true, '25');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (24, 'urgente', false, '89');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (25, 'importante', false, '45');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (26, 'incendio', true, '95');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (27, 'incendio', false, '29');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (28, 'incendio', false, '22');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (29, 'urgente', false, '94');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (30, 'importante', true, '30');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (31, 'importante', false, '75');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (32, 'urgente', true, '65');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (33, 'urgente', false, '73');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (34, 'urgente', false, '68');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (35, 'incendio', false, '78');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (36, 'incendio', false, '35');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (37, 'incendio', false, '8');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (38, 'importante', true, '20');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (39, 'urgente', true, '92');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (40, 'incendio', false, '67');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (41, 'importante', false, '26');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (42, 'incendio', true, '47');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (43, 'incendio', false, '16');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (44, 'incendio', false, '13');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (45, 'incendio', false, '41');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (46, 'urgente', false, '3');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (47, 'incendio', true, '6');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (48, 'incendio', false, '58');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (49, 'importante', true, '96');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (50, 'importante', false, '81');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (51, 'incendio', false, '66');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (52, 'urgente', true, '11');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (53, 'urgente', false, '86');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (54, 'incendio', false, '33');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (55, 'urgente', false, '55');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (56, 'urgente', false, '19');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (57, 'urgente', true, '4');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (58, 'urgente', false, '31');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (59, 'importante', true, '57');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (60, 'urgente', false, '88');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (61, 'incendio', true, '32');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (62, 'incendio', false, '48');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (63, 'urgente', false, '61');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (64, 'incendio', true, '18');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (65, 'urgente', true, '93');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (66, 'urgente', true, '84');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (67, 'incendio', false, '38');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (68, 'incendio', true, '36');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (69, 'urgente', false, '79');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (70, 'urgente', true, '34');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (71, 'urgente', false, '74');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (72, 'urgente', false, '5');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (73, 'urgente', false, '2');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (74, 'urgente', false, '97');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (75, 'incendio', true, '52');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (76, 'incendio', true, '98');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (77, 'urgente', false, '28');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (78, 'urgente', true, '71');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (79, 'urgente', true, '9');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (80, 'incendio', false, '27');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (81, 'incendio', true, '44');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (82, 'importante', false, '70');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (83, 'incendio', false, '23');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (84, 'urgente', false, '1');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (85, 'incendio', true, '24');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (86, 'urgente', true, '63');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (87, 'urgente', true, '59');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (88, 'urgente', false, '60');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (89, 'importante', true, '80');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (90, 'importante', true, '85');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (91, 'urgente', false, '51');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (92, 'importante', true, '56');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (93, 'urgente', false, '15');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (94, 'incendio', true, '64');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (95, 'importante', true, '7');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (96, 'urgente', true, '62');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (97, 'importante', false, '53');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (98, 'importante', false, '14');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (99, 'importante', false, '46');
insert into tarea (id_tarea, asunto_tarea, estado_tarea, id_emergencia) values (100, 'incendio', true, '94');

-- ranking

insert into ranking (id_ranking, id_tarea, id_voluntario, puntaje) values (1, '61', '15', 699.66);
insert into ranking (id_ranking, id_tarea, id_voluntario, puntaje) values (2, '72', '19', 596.99);
insert into ranking (id_ranking, id_tarea, id_voluntario, puntaje) values (3, '53', '60', 664.04);
insert into ranking (id_ranking, id_tarea, id_voluntario, puntaje) values (4, '42', '46', 742.26);
insert into ranking (id_ranking, id_tarea, id_voluntario, puntaje) values (5, '26', '93', 460.92);
insert into ranking (id_ranking, id_tarea, id_voluntario, puntaje) values (6, '65', '22', 599.08);
insert into ranking (id_ranking, id_tarea, id_voluntario, puntaje) values (7, '91', '80', 673.43);
insert into ranking (id_ranking, id_tarea, id_voluntario, puntaje) values (8, '99', '97', 525.85);
insert into ranking (id_ranking, id_tarea, id_voluntario, puntaje) values (9, '92', '13', 623.62);
insert into ranking (id_ranking, id_tarea, id_voluntario, puntaje) values (10, '23', '65', 642.71);
insert into ranking (id_ranking, id_tarea, id_voluntario, puntaje) values (11, '46', '24', 594.57);
insert into ranking (id_ranking, id_tarea, id_voluntario, puntaje) values (12, '73', '32', 635.38);
insert into ranking (id_ranking, id_tarea, id_voluntario, puntaje) values (13, '55', '35', 832.05);
insert into ranking (id_ranking, id_tarea, id_voluntario, puntaje) values (14, '93', '85', 648.69);
insert into ranking (id_ranking, id_tarea, id_voluntario, puntaje) values (15, '32', '8', 463.68);
insert into ranking (id_ranking, id_tarea, id_voluntario, puntaje) values (16, '45', '18', 582.45);
insert into ranking (id_ranking, id_tarea, id_voluntario, puntaje) values (17, '28', '86', 523.58);
insert into ranking (id_ranking, id_tarea, id_voluntario, puntaje) values (18, '54', '70', 550.66);
insert into ranking (id_ranking, id_tarea, id_voluntario, puntaje) values (19, '7', '100', 488.46);
insert into ranking (id_ranking, id_tarea, id_voluntario, puntaje) values (20, '22', '53', 742.14);
insert into ranking (id_ranking, id_tarea, id_voluntario, puntaje) values (21, '36', '3', 747.41);
insert into ranking (id_ranking, id_tarea, id_voluntario, puntaje) values (22, '6', '30', 860.16);
insert into ranking (id_ranking, id_tarea, id_voluntario, puntaje) values (23, '57', '87', 374.1);
insert into ranking (id_ranking, id_tarea, id_voluntario, puntaje) values (24, '41', '78', 514.91);
insert into ranking (id_ranking, id_tarea, id_voluntario, puntaje) values (25, '64', '66', 503.08);
insert into ranking (id_ranking, id_tarea, id_voluntario, puntaje) values (26, '60', '34', 493.65);
insert into ranking (id_ranking, id_tarea, id_voluntario, puntaje) values (27, '18', '76', 648.75);
insert into ranking (id_ranking, id_tarea, id_voluntario, puntaje) values (28, '66', '58', 566.24);
insert into ranking (id_ranking, id_tarea, id_voluntario, puntaje) values (29, '4', '9', 660.97);
insert into ranking (id_ranking, id_tarea, id_voluntario, puntaje) values (30, '100', '98', 523.38);

-- habilidad

insert into habilidad (id_habilidad, habilidad) values (1, 'HAZMAT');
insert into habilidad (id_habilidad, habilidad) values (2, 'HAZMAT');
insert into habilidad (id_habilidad, habilidad) values (3, 'ESCALA');
insert into habilidad (id_habilidad, habilidad) values (4, 'ESCALA');
insert into habilidad (id_habilidad, habilidad) values (5, 'RCP');
insert into habilidad (id_habilidad, habilidad) values (6, 'ESCALA');
insert into habilidad (id_habilidad, habilidad) values (7, 'FUEGO BASICO');
insert into habilidad (id_habilidad, habilidad) values (8, 'FUEGO BASICO');
insert into habilidad (id_habilidad, habilidad) values (9, 'RCP');
insert into habilidad (id_habilidad, habilidad) values (10, 'ESCALA');
insert into habilidad (id_habilidad, habilidad) values (11, 'HAZMAT');
insert into habilidad (id_habilidad, habilidad) values (12, 'HAZMAT');
insert into habilidad (id_habilidad, habilidad) values (13, 'FUEGO AVANZADO');
insert into habilidad (id_habilidad, habilidad) values (14, 'ESCALA');
insert into habilidad (id_habilidad, habilidad) values (15, 'FUEGO BASICO');
insert into habilidad (id_habilidad, habilidad) values (16, 'HAZMAT');
insert into habilidad (id_habilidad, habilidad) values (17, 'FUEGO BASICO');
insert into habilidad (id_habilidad, habilidad) values (18, 'HAZMAT');
insert into habilidad (id_habilidad, habilidad) values (19, 'FUEGO BASICO');
insert into habilidad (id_habilidad, habilidad) values (20, 'FUEGO AVANZADO');

--	vol_habilidad

insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (1, '68', '10');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (2, '21', '5');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (3, '63', '17');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (4, '4', '8');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (5, '98', '13');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (6, '87', '11');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (7, '50', '15');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (8, '17', '12');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (9, '31', '6');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (10, '41', '19');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (11, '8', '18');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (12, '56', '16');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (13, '80', '1');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (14, '1', '20');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (15, '100', '3');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (16, '77', '7');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (17, '95', '14');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (18, '79', '2');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (19, '53', '9');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (20, '5', '4');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (21, '49', '6');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (22, '28', '1');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (23, '7', '12');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (24, '90', '5');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (25, '47', '17');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (26, '3', '13');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (27, '89', '3');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (28, '81', '15');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (29, '86', '14');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (30, '24', '4');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (31, '58', '20');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (32, '2', '11');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (33, '14', '2');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (34, '70', '10');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (35, '57', '8');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (36, '29', '19');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (37, '74', '9');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (38, '48', '18');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (39, '61', '7');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (40, '35', '16');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (41, '69', '16');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (42, '43', '11');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (43, '22', '9');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (44, '85', '17');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (45, '44', '8');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (46, '6', '18');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (47, '76', '13');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (48, '51', '10');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (49, '32', '1');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (50, '39', '20');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (51, '38', '2');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (52, '25', '14');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (53, '19', '3');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (54, '11', '6');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (55, '13', '19');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (56, '73', '5');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (57, '67', '7');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (58, '88', '4');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (59, '82', '12');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (60, '54', '15');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (61, '60', '18');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (62, '93', '2');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (63, '46', '13');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (64, '12', '8');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (65, '9', '3');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (66, '72', '12');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (67, '91', '4');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (68, '75', '15');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (69, '37', '20');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (70, '62', '5');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (71, '45', '11');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (72, '84', '10');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (73, '42', '14');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (74, '99', '7');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (75, '40', '6');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (76, '96', '1');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (77, '64', '17');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (78, '27', '19');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (79, '94', '9');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (80, '65', '16');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (81, '34', '16');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (82, '55', '11');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (83, '59', '14');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (84, '10', '7');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (85, '52', '6');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (86, '18', '18');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (87, '16', '20');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (88, '30', '5');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (89, '23', '13');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (90, '20', '15');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (91, '83', '2');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (92, '15', '12');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (93, '92', '1');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (94, '33', '4');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (95, '36', '10');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (96, '97', '9');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (97, '26', '17');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (98, '78', '3');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (99, '66', '8');
insert into vol_habilidad (id_vol_habilidad, id_voluntario, id_habilidad) values (100, '71', '19');

--eme_habilidad

insert into eme_habilidad (id_eme_habilidad, id_habilidad, id_emergencia) values (1, '6', '87');
insert into eme_habilidad (id_eme_habilidad, id_habilidad, id_emergencia) values (2, '3', '28');
insert into eme_habilidad (id_eme_habilidad, id_habilidad, id_emergencia) values (3, '14', '13');
insert into eme_habilidad (id_eme_habilidad, id_habilidad, id_emergencia) values (4, '16', '2');
insert into eme_habilidad (id_eme_habilidad, id_habilidad, id_emergencia) values (5, '15', '64');
insert into eme_habilidad (id_eme_habilidad, id_habilidad, id_emergencia) values (6, '13', '51');
insert into eme_habilidad (id_eme_habilidad, id_habilidad, id_emergencia) values (7, '12', '44');
insert into eme_habilidad (id_eme_habilidad, id_habilidad, id_emergencia) values (8, '11', '62');
insert into eme_habilidad (id_eme_habilidad, id_habilidad, id_emergencia) values (9, '19', '52');
insert into eme_habilidad (id_eme_habilidad, id_habilidad, id_emergencia) values (10, '10', '93');
insert into eme_habilidad (id_eme_habilidad, id_habilidad, id_emergencia) values (11, '9', '94');
insert into eme_habilidad (id_eme_habilidad, id_habilidad, id_emergencia) values (12, '7', '49');
insert into eme_habilidad (id_eme_habilidad, id_habilidad, id_emergencia) values (13, '17', '16');
insert into eme_habilidad (id_eme_habilidad, id_habilidad, id_emergencia) values (14, '2', '7');
insert into eme_habilidad (id_eme_habilidad, id_habilidad, id_emergencia) values (15, '4', '83');
insert into eme_habilidad (id_eme_habilidad, id_habilidad, id_emergencia) values (16, '5', '15');
insert into eme_habilidad (id_eme_habilidad, id_habilidad, id_emergencia) values (17, '1', '91');
insert into eme_habilidad (id_eme_habilidad, id_habilidad, id_emergencia) values (18, '18', '6');
insert into eme_habilidad (id_eme_habilidad, id_habilidad, id_emergencia) values (19, '20', '47');
insert into eme_habilidad (id_eme_habilidad, id_habilidad, id_emergencia) values (20, '8', '35');

-- tarea_habilidad

insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (1, '52', '13');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (2, '7', '14');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (3, '57', '17');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (4, '22', '11');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (5, '60', '2');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (6, '76', '19');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (7, '42', '12');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (8, '56', '9');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (9, '89', '10');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (10, '36', '5');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (11, '2', '6');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (12, '31', '7');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (13, '39', '3');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (14, '80', '20');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (15, '96', '1');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (16, '67', '15');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (17, '74', '8');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (18, '87', '18');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (19, '54', '4');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (20, '84', '16');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (21, '9', '5');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (22, '41', '3');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (23, '58', '19');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (24, '37', '16');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (25, '92', '18');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (26, '44', '10');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (27, '98', '20');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (28, '8', '7');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (29, '25', '17');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (30, '38', '2');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (31, '53', '13');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (32, '35', '15');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (33, '40', '8');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (34, '64', '9');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (35, '18', '6');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (36, '27', '4');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (37, '45', '11');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (38, '50', '12');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (39, '12', '14');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (40, '59', '1');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (41, '6', '1');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (42, '10', '14');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (43, '69', '7');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (44, '86', '12');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (45, '49', '8');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (46, '16', '13');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (47, '13', '6');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (48, '34', '16');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (49, '47', '3');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (50, '81', '2');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (51, '88', '19');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (52, '55', '11');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (53, '20', '15');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (54, '94', '4');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (55, '43', '20');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (56, '21', '18');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (57, '63', '10');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (58, '79', '5');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (59, '99', '17');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (60, '28', '9');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (61, '51', '1');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (62, '70', '19');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (63, '90', '14');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (64, '75', '7');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (65, '1', '18');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (66, '15', '17');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (67, '30', '16');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (68, '14', '10');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (69, '82', '4');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (70, '91', '20');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (71, '17', '12');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (72, '46', '11');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (73, '97', '5');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (74, '71', '2');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (75, '78', '9');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (76, '24', '8');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (77, '85', '3');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (78, '72', '6');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (79, '4', '15');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (80, '32', '13');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (81, '77', '20');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (82, '100', '19');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (83, '95', '17');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (84, '11', '10');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (85, '62', '13');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (86, '61', '5');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (87, '3', '18');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (88, '23', '1');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (89, '65', '8');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (90, '26', '15');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (91, '83', '9');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (92, '19', '16');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (93, '66', '7');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (94, '33', '6');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (95, '93', '12');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (96, '48', '3');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (97, '68', '11');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (98, '29', '2');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (99, '5', '4');
insert into tarea_habilidad (id_tarea_habilidad, id_tarea, id_habilidad) values (100, '45', '14');

